apiVersion: v1
data:
  MYSQL_DATABASE: bXlzcWwtZGI=
  MYSQL_PASSWORD: bXl1c2VycGFzc3dvcmQ=
  MYSQL_ROOT_PASSWORD: bXlyb290cGFzc3dvcmQ=
  MYSQL_USER: cmFodWw=
kind: Secret
metadata:
  name: mysql-secret
