apiVersion: v1
data:
  database: c3FsZGI=
  root_password: bXlyb290cGFzc3dvcmQxMjM=
  user: cmFodWw=
  user_password: bXl1c2VycGFzc3dvcmQxMjM=
kind: Secret
metadata:
  creationTimestamp: null
  name: db-secret
